-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 23:02:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appdb` DEFAULT CHARACTER SET utf8 ;
USE `appdb` ;

-- -----------------------------------------------------
-- Table `appdb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`client` (
  `cltID` CHAR(255) NOT NULL,
  `cltToken` VARCHAR(255) NULL,
  `cltUsername` VARCHAR(50) NOT NULL,
  `cltFirstName` VARCHAR(50) NOT NULL,
  `cltLastName` VARCHAR(50) NOT NULL,
  `cltEmail` VARCHAR(50) NOT NULL,
  `cltPfpName` VARCHAR(255) NULL,
  `cltPhoneNumber` CHAR(10) NOT NULL,
  `cltPassword` VARCHAR(255) NOT NULL,
  `cltSignupDate` DATETIME NOT NULL DEFAULT NOW(),
  `cltVerifiedEmail` TINYINT NOT NULL DEFAULT 0,
  `cltIsModerator` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cltID`),
  UNIQUE INDEX `cltEmail_UNIQUE` (`cltEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`address` (
  `adrID` CHAR(255) NOT NULL,
  `adrAddress` VARCHAR(255) NOT NULL,
  `adrAddressOptional` VARCHAR(255) NOT NULL,
  `adrPostalCode` VARCHAR(255) NOT NULL,
  `adrCity` VARCHAR(45) NOT NULL,
  `adrDefault` TINYINT NOT NULL DEFAULT 0,
  `Client_cltID` CHAR(255) NOT NULL,
  PRIMARY KEY (`adrID`, `Client_cltID`),
  INDEX `fk_Address_Client1_idx` (`Client_cltID` ASC),
  CONSTRAINT `fk_Address_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`product` (
  `prdID` CHAR(255) NOT NULL,
  `prdName` VARCHAR(30) NOT NULL,
  `prdPrice` DECIMAL(10,2) NOT NULL,
  `prdReleaseDate` DATE NOT NULL,
  PRIMARY KEY (`prdID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`basket` (
  `basID` CHAR(255) NOT NULL,
  `basDate` DATETIME NOT NULL DEFAULT NOW(),
  `Client_cltID` CHAR(255) NOT NULL,
  PRIMARY KEY (`basID`, `Client_cltID`),
  INDEX `fk_Basket_Client1_idx` (`Client_cltID` ASC),
  CONSTRAINT `fk_Basket_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`order_history` (
  `orhID` CHAR(255) NOT NULL,
  `orhStatus` VARCHAR(10) NOT NULL,
  `orhDate` DATE NOT NULL,
  `Client_cltID` CHAR(255) NOT NULL,
  PRIMARY KEY (`orhID`, `Client_cltID`),
  INDEX `fk_Order_History_Client1_idx` (`Client_cltID` ASC),
  CONSTRAINT `fk_Order_History_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`device` (
  `devID` CHAR(255) NOT NULL,
  `devName` VARCHAR(255) NOT NULL,
  `prdID` VARCHAR(255) NOT NULL,
  `prcColor` VARCHAR(255) NOT NULL,
  `Client_cltID` CHAR(255) NOT NULL,
  PRIMARY KEY (`devID`, `Client_cltID`),
  INDEX `fk_Device_Client1_idx` (`Client_cltID` ASC),
  CONSTRAINT `fk_Device_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`product_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`product_list` (
  `prdLstID` CHAR(255) NOT NULL,
  `prcColor` VARCHAR(255) NULL,
  `Product_prdID` CHAR(255) NOT NULL,
  `Basket_basID` CHAR(255) NOT NULL,
  PRIMARY KEY (`prdLstID`, `Product_prdID`, `Basket_basID`),
  INDEX `fk_Product_List_Product_idx` (`Product_prdID` ASC),
  INDEX `fk_Product_List_Basket1_idx` (`Basket_basID` ASC),
  CONSTRAINT `fk_Product_List_Product`
    FOREIGN KEY (`Product_prdID`)
    REFERENCES `appdb`.`product` (`prdID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_List_Basket1`
    FOREIGN KEY (`Basket_basID`)
    REFERENCES `appdb`.`basket` (`basID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`data_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`data_device` (
  `dapID` CHAR(255) NOT NULL,
  `dapBPM` VARCHAR(255) NOT NULL,
  `dapLatitude` VARCHAR(255) NOT NULL,
  `dapLongitude` VARCHAR(255) NOT NULL,
  `dapCO2` VARCHAR(255) NOT NULL,
  `dapDecibel` VARCHAR(255) NOT NULL,
  `dapTemp` VARCHAR(255) NOT NULL,
  `dapDate` VARCHAR(255) NOT NULL,
  `Device_devID` CHAR(255) NOT NULL,
  PRIMARY KEY (`dapID`, `Device_devID`),
  INDEX `fk_Data_Device_Device1_idx` (`Device_devID` ASC),
  CONSTRAINT `fk_Data_Device_Device1`
    FOREIGN KEY (`Device_devID`)
    REFERENCES `appdb`.`device` (`devID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`payment_method` (
  `mdpID` CHAR(255) NOT NULL,
  `pamType` VARCHAR(20) NOT NULL,
  `pamCardNum` CHAR(16) NOT NULL,
  `pamCVV` CHAR(3) NOT NULL,
  `pamCardExpiryDate` CHAR(4) NOT NULL,
  `Client_cltID` CHAR(255) NOT NULL,
  PRIMARY KEY (`mdpID`, `Client_cltID`),
  INDEX `fk_Payment_Method_Client1_idx` (`Client_cltID` ASC),
  CONSTRAINT `fk_Payment_Method_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`admin` (
  `admID` CHAR(255) NOT NULL,
  `admToken` VARCHAR(255) NULL,
  `admUsername` VARCHAR(20) NOT NULL,
  `admFirstName` VARCHAR(255) NULL,
  `admLastName` VARCHAR(255) NULL,
  `admEmail` VARCHAR(30) NOT NULL,
  `admPfpName` VARCHAR(255) NULL,
  `admPhoneNumber` CHAR(10) NULL,
  `admPassword` VARCHAR(255) NOT NULL,
  `admSignupDate` DATETIME NULL DEFAULT NOW(),
  `admVerifiedEmail` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`admID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`session_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`session_message` (
  `sesMsgID` VARCHAR(255) NOT NULL,
  `sesMsgStartDate` DATETIME NOT NULL DEFAULT NOW(),
  `sesMsgEndDate` DATETIME NULL,
  `Client_cltID` CHAR(255) NOT NULL,
  PRIMARY KEY (`sesMsgID`, `Client_cltID`),
  INDEX `fk_Session_Message_Client1_idx` (`Client_cltID` ASC),
  CONSTRAINT `fk_Session_Message_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`client_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`client_message` (
  `cltMsgID` CHAR(255) NOT NULL,
  `cltMsgMessage` VARCHAR(255) NOT NULL,
  `cltMsgDate` DATETIME NOT NULL DEFAULT NOW(),
  `Client_cltID` CHAR(255) NOT NULL,
  `Session_Message_sesMsgID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cltMsgID`, `Client_cltID`, `Session_Message_sesMsgID`),
  INDEX `fk_Client_Message_Client1_idx` (`Client_cltID` ASC),
  INDEX `fk_Client_Message_Session_Message1_idx` (`Session_Message_sesMsgID` ASC),
  CONSTRAINT `fk_Client_Message_Client1`
    FOREIGN KEY (`Client_cltID`)
    REFERENCES `appdb`.`client` (`cltID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Client_Message_Session_Message1`
    FOREIGN KEY (`Session_Message_sesMsgID`)
    REFERENCES `appdb`.`session_message` (`sesMsgID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`image` (
  `imgID` CHAR(255) NOT NULL,
  `imgPath` VARCHAR(255) NOT NULL,
  `imgCategory` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`imgID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`assistance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`assistance` (
  `astID` CHAR(255) NOT NULL,
  `astQuestion` VARCHAR(255) NOT NULL,
  `astAnswer` VARCHAR(255) NULL,
  `astDate` DATE NOT NULL DEFAULT now(),
  `astApproved` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`astID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`question` (
  `qstID` CHAR(255) NOT NULL,
  `qstQuestion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`qstID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`question_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`question_answers` (
  `qstRepID` CHAR(255) NOT NULL,
  `qstRepAnswer` VARCHAR(255) NOT NULL,
  `qstRepBool` TINYINT NOT NULL,
  `Question_qstID` CHAR(255) NOT NULL,
  PRIMARY KEY (`qstRepID`, `Question_qstID`),
  INDEX `fk_Question_Answers_Question1_idx` (`Question_qstID` ASC),
  CONSTRAINT `fk_Question_Answers_Question1`
    FOREIGN KEY (`Question_qstID`)
    REFERENCES `appdb`.`question` (`qstID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`admin_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`admin_message` (
  `admMsgID` CHAR(255) NOT NULL,
  `admMsgMessage` VARCHAR(255) NOT NULL,
  `admMsgDate` DATETIME NOT NULL DEFAULT NOW(),
  `Admin_admID` CHAR(255) NOT NULL,
  `Session_Message_sesMsgID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`admMsgID`, `Admin_admID`, `Session_Message_sesMsgID`),
  INDEX `fk_Admin_Message_Admin1_idx` (`Admin_admID` ASC),
  INDEX `fk_Admin_Message_Session_Message1_idx` (`Session_Message_sesMsgID` ASC),
  CONSTRAINT `fk_Admin_Message_Admin1`
    FOREIGN KEY (`Admin_admID`)
    REFERENCES `appdb`.`admin` (`admID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Admin_Message_Session_Message1`
    FOREIGN KEY (`Session_Message_sesMsgID`)
    REFERENCES `appdb`.`session_message` (`sesMsgID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`product_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`product_color` (
  `prcID` VARCHAR(255) NOT NULL,
  `prcColor` VARCHAR(255) NOT NULL,
  `Product_prdID` CHAR(255) NOT NULL,
  PRIMARY KEY (`prcID`, `Product_prdID`),
  INDEX `fk_Product_Color_Product1_idx` (`Product_prdID` ASC),
  CONSTRAINT `fk_Product_Color_Product1`
    FOREIGN KEY (`Product_prdID`)
    REFERENCES `appdb`.`product` (`prdID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appdb`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appdb`.`product_image` (
  `pimID` VARCHAR(255) NOT NULL,
  `pimPath` VARCHAR(255) NOT NULL,
  `Product_Color_prcID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pimID`, `Product_Color_prcID`),
  INDEX `fk_Product_Image_Product_Color1_idx` (`Product_Color_prcID` ASC),
  CONSTRAINT `fk_Product_Image_Product_Color1`
    FOREIGN KEY (`Product_Color_prcID`)
    REFERENCES `appdb`.`product_color` (`prcID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
